before:
  hooks:
  - go mod tidy
builds:
  -
    main: gwebc.go
    id: "gwebc"
    binary: gwebc
    ldflags: -H windowsgui
    goos:
      - windows
    goarch:
      - amd64
    hooks:
      pre: build.cmd 
      post: build.cmd 
archives:
  - 
    format: binary
